apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-sql-kube
data:
  application.yml: |-
    spring:
      config:
        activate:
          on-profile: kubernetes
      cloud:
        gcp:
          sql:
            enabled: "true"
            database-name: postgres
            instance-connection-name: "joe-experimental-project:us-central1:quote-db-instance"