apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  labels:
    run: postgres
spec:
  selector:
    matchLabels:
      run: postgres
  replicas: 1
  template:
    metadata:
      labels:
        run: postgres
    spec:
      containers:
      - name: demo-db
        image: postgres:13
        ports:
        - containerPort: 5432
          name: db-port
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "123456"
        - name: POSTGRES_DATABASE
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    run: postgres
spec:
  selector:
    run: postgres
  ports:
  - name: db-port
    protocol: TCP
    port: 5432
    targetPort: db-port
