version: '2'

services:
  app:
    image: 'demo-sql-kube:latest'
    build:
      context: .
    container_name: app
    ports:
    - "8080:8080"
    environment:
    - SPRING_CLOUD_GCP_SQL_ENABLED=true
    - SPRING_CLOUD_GCP_SQL_INSTANCE-CONNECTION-NAME=joe-experimental-project:us-central1:quote-db-instance
