server:
  port: 8080
spring:
  application:
    name: demo-sql-kube
  cloud:
    gcp:
      sql:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      continue-on-error: true
      mode: always
